language: php
dist: xenial

matrix:
  fast_finish: true
  include:
    - php: 8.0
    - php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
      dist: trusty
    - php: 5.4
      dist: trusty

before_install:
  - sh .travis.install

script:
  - TESTS_GPG_BINARY=/usr/bin/gpg2 vendor/bin/phpunit --coverage-text tests
