name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: true
      matrix:
        php: ["5.4", "5.5", "5.6", "7.0", "7.1", "7.2", "7.3", "7.4", "8.0"]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: olafurpg/setup-gpg@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, posix
          coverage: none

      - name: Setup problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name:
        if: matrix.php < 7.4
        run: |
          composer require --dev 'phpunit/phpunit:^4.8.36 || ^5.7.21 || ^6 || ^7' --no-update
          sed -i 's/: void//g' tests/*.php

      - name: Fix PHPUnit for PHP 8.0
        if: matrix.php >= 8.0
        run: composer config platform.php 7.4

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: GnuPG version
        run: gpg --version

      - name: Execute tests
        run: TESTS_GPG_BINARY=/home/runner/work/Crypt_GPG/Crypt_GPG/gnupg-1.4.23/g10/gpg vendor/bin/phpunit --stop-on-error tests

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: tests/debug.log
